### ISSUE TITLE
Is this bug?

### ISSUE THREAD

**Issue by rf0321** [Ghostrick/node-googlehome#2]
Run this test code then, cause error like a below.
```javascript
const GoogleHome = require('node-googlehome')

GoogleHome.search(1000)
  .then(resp => { console.log(resp) })

var device = new GoogleHome.Connecter('192.168.25.52')

device.config({lang: 'ja'})

device.speak('こんにちは！')
  .then(console.log)
  .catch(console.log)
 ```
Error log(search.js line of 6)
```
  let services = []
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/xxxxxx/my_projects/GoogleHome/nodejs/node_modules/node-googlehome/index.js:1:78)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by ghostrick** [comment]
@ItinoseSan What is the version of node.js that you are using?

**Comment by rf0321** [comment]
@Ghostrick Im using v4.8.4 now. I think maybe this error relations difference of version.

**Comment by ghostrick** [comment]
@ItinoseSan Version v7 or higher is required for this library. Please read the README.md .

**Comment by rf0321** [comment]
@Ghostrick Very Sorry!
